const ROADMAP_TOPICS = [
  {
    name: "Arrays",
    questions: [
      "Set Matrix Zeroes",
      "Pascal's Triangle I",
      "Next Permutation",
      "Kadane's Algorithm",
      "Sort an array of 0's 1's and 2's",
      "Stock Buy and Sell",
    ],
  },
  {
    name: "Arrays Part-II",
    questions: [
      "Rotate matrix by 90 degrees",
      "Merge Overlapping Subintervals",
      "Merge two sorted arrays without extra space",
      "Find the Duplicate Number",
      "Find the repeating and missing number",
      "Inversion of Array (Pre-req: Merge Sort)",
    ],
  },
  {
    name: "Arrays Part-III",
    questions: [
      "Search in a 2D matrix",
      "Pow(x, n)",
      "Majority Element-I",
      "Majority Element-II",
      "Grid unique paths",
      "Reverse Pairs",
    ],
  },
  {
    name: "Arrays Part-IV",
    questions: [
      "Two Sum",
      "4 Sum",
      "Longest Consecutive Sequence in an Array",
      "Largest Subarray with K sum",
      "Count subarrays with given xor K",
      "Longest Substring Without Repeating Characters",
    ],
  },
  {
    name: "Linked List",
    questions: [
      "Reverse a LL",
      "Find Middle of Linked List",
      "Merge two Sorted Lists",
      "Remove Nth node from the back of the LL",
      "Add two numbers as LinkedList",
      "Delete Node in a Linked List O(1)",
    ],
  },
  {
    name: "Linked List Part-II",
    questions: [
      "Find the intersection point of Y LL",
      "Detect a loop in LL",
      "Reverse LL in group of given size K",
      "Check if LL is palindrome or not",
      "Find the starting point in LL",
      "Flattening of LL",
    ],
  },
  {
    name: "Linked List and Arrays",
    questions: [
      "Rotate a LL",
      "Clone a LL with random and next pointer",
      "3 Sum",
      "Trapping Rainwater",
      "Remove duplicates from sorted array",
      "Maximum Consecutive Ones",
    ],
  },
  {
    name: "Greedy Algorithm",
    questions: [
      "N meetings in one room",
      "Minimum number of platforms required for a railway",
      "Job sequencing Problem",
      "Fractional Knapsack",
      "Minimum coins",
      "Assign Cookies",
    ],
  },
  {
    name: "Recursion",
    questions: [
      "Subset Sums",
      "Subsets II",
      "Combination Sum",
      "Combination Sum II",
      "Palindrome partitioning",
      "Permutation Sequence",
    ],
  },
  {
    name: "Recursion and Backtracking",
    questions: [
      "Permutations of a String",
      "N Queen",
      "Sudoku Solver",
      "M Coloring Problem",
      "Rat in a Maze",
      "Word Break (print all ways)",
    ],
  },
  {
    name: "Binary Search",
    questions: [
      "The N-th root of an integer",
      "Matrix Median",
      "Single element in sorted array",
      "Search element in a sorted and rotated array / find pivot",
      "Median of 2 sorted arrays",
      "Kth element of 2 sorted arrays",
      "Allocate Minimum Number of Pages",
      "Aggressive Cows",
    ],
  },
  {
    name: "Heaps",
    questions: [
      "Implement Max Heap",
      "K-th Largest element in an array",
      "Maximum Sum Combination",
      "Find Median from Data Stream",
      "Merge K Sorted Arrays",
      "Top K Frequent Elements",
    ],
  },
  {
    name: "Stack and Queue",
    questions: [
      "Implement Stack using Arrays",
      "Implement Queue using Arrays",
      "Implement Stack using Queue (single queue)",
      "Implement Queue using Stack",
      "Balanced Parenthesis",
      "Next Greater Element",
      "Sort a Stack",
    ],
  },
  {
    name: "Stack and Queue Part-II",
    questions: [
      "Next Smaller Element",
      "LRU Cache",
      "LFU Cache",
      "Largest rectangle in a histogram",
      "Sliding Window Maximum",
      "Implement Min Stack",
      "Rotten Oranges",
      "Stock span problem",
      "Maximum of Minimums for Every Window Size",
      "Celebrity Problem",
    ],
  },
  {
    name: "String",
    questions: [
      "Reverse every word in a string",
      "Longest Palindrome in a string",
      "Roman to Integer",
      "Implement ATOI / STRSTR",
      "Longest Common Prefix",
      "Rabin Karp Algorithm",
    ],
  },
  {
    name: "String Part-II",
    questions: [
      "Z function",
      "KMP Algorithm or LPS array",
      "Minimum insertions to make string palindrome",
      "Valid Anagram",
      "Count and say",
      "Compare version numbers",
    ],
  },
  {
    name: "Binary Tree",
    questions: [
      "Inorder Traversal",
      "Preorder Traversal",
      "Postorder Traversal",
      "Morris Inorder Traversal",
      "Morris Preorder Traversal",
      "Right/Left View of BT",
      "Bottom view of BT",
      "Top View of BT",
      "Pre, Post, Inorder in one traversal",
      "Vertical Order Traversal",
      "Print root to leaf path in BT",
      "Maximum Width of BT",
    ],
  },
  {
    name: "Binary Tree Part-II",
    questions: [
      "Level Order Traversal",
      "Maximum Depth in BT",
      "Diameter of Binary Tree",
      "Check for balanced binary tree",
      "LCA in BT",
      "Check if two trees are identical",
      "Zig Zag / Spiral Traversal",
      "Boundary Traversal",
    ],
  },
  {
    name: "Binary Tree Part-III",
    questions: [
      "Maximum path sum",
      "Construct BT from Preorder and Inorder",
      "Construct BT from Postorder and Inorder",
      "Symmetric Binary Tree",
      "Flatten Binary Tree to Linked List",
      "Check for symmetrical BTs",
      "Children Sum Property",
    ],
  },
  {
    name: "Binary Search Tree",
    questions: [
      "Populating Next Right Pointers",
      "Search in BST",
      "Construct BST from given keys",
      "Construct BST from preorder traversal",
      "Check if a tree is a BST",
      "LCA in BST",
      "Inorder successor and predecessor in BST",
    ],
  },
  {
    name: "Binary Search Tree Part-II",
    questions: [
      "Floor in a BST",
      "Ceil in a BST",
      "Find K-th smallest element in BST",
      "Kth Smallest and Largest element in BST",
      "Two sum in BST",
      "BST iterator",
      "Size of the largest BST in a Binary Tree",
      "Serialize and De-serialize BT",
    ],
  },
  {
    name: "Binary Trees [Miscellaneous]",
    questions: [
      "Binary Tree to Doubly Linked List",
      "Find Median in a Stream",
      "Kth largest element in a stream",
      "Distinct Numbers in Each Subarray",
      "K-th largest element in an unsorted array",
      "Flood-fill Algorithm",
    ],
  },
  {
    name: "Graph",
    questions: [
      "Clone Graph",
      "DFS",
      "Traversal Techniques",
      "Detect cycle in Undirected Graph (BFS)",
      "Detect cycle in Undirected Graph (DFS)",
      "Detect cycle in Directed Graph (DFS)",
      "Detect cycle in Directed Graph (BFS)",
      "Topological Sort BFS",
      "Topological Sort DFS",
      "Number of Islands",
      "Bipartite Graph",
      "Bipartite Check using DFS",
    ],
  },
  {
    name: "Graph Part-II",
    questions: [
      "Strongly Connected Component (Kosaraju)",
      "Dijkstra's Algorithm",
      "Bellman Ford Algorithm",
      "Floyd Warshall Algorithm",
      "MST using Prim's",
      "MST using Kruskal",
    ],
  },
  {
    name: "Dynamic Programming",
    questions: [
      "Max Product Subarray",
      "Longest Increasing Subsequence",
      "Longest Common Subsequence",
      "0/1 Knapsack",
      "Edit Distance",
      "Maximum Sum Increasing Subsequence",
      "Matrix Chain Multiplication",
    ],
  },
  {
    name: "Dynamic Programming Part-II",
    questions: [
      "Minimum Sum Path in Matrix",
      "Coin Change II",
      "Subset Sum equals target",
      "Rod Cutting Problem",
      "Super Egg Drop",
      "Word Break",
      "Palindrome Partitioning (MCM Variation)",
      "Maximum Profit in Job Scheduling",
    ],
  },
  {
    name: "Trie",
    questions: [
      "Trie Implementation and Operations",
      "Trie Implementation and Advanced Operations",
      "Longest Word with All Prefixes",
      "Number of distinct substrings in a string",
      "Power Set",
      "Maximum XOR of two numbers in an array",
    ],
  },
];

// Added: centralized difficulty ranking map requested for each roadmap question.
const DIFFICULTY_BY_QUESTION = {
  "Set Matrix Zeroes": "Medium",
  "Pascal's Triangle I": "Easy",
  "Next Permutation": "Medium",
  "Kadane's Algorithm": "Medium",
  "Sort an array of 0's 1's and 2's": "Medium",
  "Stock Buy and Sell": "Medium",
  "Rotate matrix by 90 degrees": "Medium",
  "Merge Overlapping Subintervals": "Medium",
  "Merge two sorted arrays without extra space": "Medium",
  "Find the Duplicate Number": "Medium",
  "Find the repeating and missing number": "Hard",
  "Inversion of Array (Pre-req: Merge Sort)": "Hard",
  "Search in a 2D matrix": "Hard",
  "Pow(x, n)": "Easy",
  "Majority Element-I": "Easy",
  "Majority Element-II": "Hard",
  "Grid unique paths": "Medium",
  "Reverse Pairs": "Hard",
  "Two Sum": "Easy",
  "4 Sum": "Medium",
  "Longest Consecutive Sequence in an Array": "Medium",
  "Largest Subarray with K sum": "Medium",
  "Count subarrays with given xor K": "Hard",
  "Longest Substring Without Repeating Characters": "Medium",
  "Reverse a LL": "Medium",
  "Find Middle of Linked List": "Easy",
  "Merge two Sorted Lists": "Hard",
  "Remove Nth node from the back of the LL": "Medium",
  "Add two numbers as LinkedList": "Medium",
  "Delete Node in a Linked List O(1)": "Medium",
  "Find the intersection point of Y LL": "Medium",
  "Detect a loop in LL": "Medium",
  "Reverse LL in group of given size K": "Hard",
  "Check if LL is palindrome or not": "Medium",
  "Find the starting point in LL": "Medium",
  "Flattening of LL": "Hard",
  "Rotate a LL": "Hard",
  "Clone a LL with random and next pointer": "Hard",
  "3 Sum": "Medium",
  "Trapping Rainwater": "Hard",
  "Remove duplicates from sorted array": "Easy",
  "Maximum Consecutive Ones": "Easy",
  "N meetings in one room": "Medium",
  "Minimum number of platforms required for a railway": "Medium",
  "Job sequencing Problem": "Medium",
  "Fractional Knapsack": "Medium",
  "Minimum coins": "Hard",
  "Assign Cookies": "Easy",
  "Subset Sums": "Hard",
  "Subsets II": "Medium",
  "Combination Sum": "Medium",
  "Combination Sum II": "Medium",
  "Palindrome partitioning": "Hard",
  "Permutation Sequence": "Medium",
  "Permutations of a String": "Medium",
  "N Queen": "Hard",
  "Sudoku Solver": "Hard",
  "M Coloring Problem": "Hard",
  "Rat in a Maze": "Hard",
  "Word Break (print all ways)": "Medium",
  "The N-th root of an integer": "Medium",
  "Matrix Median": "Hard",
  "Single element in sorted array": "Medium",
  "Search element in a sorted and rotated array / find pivot": "Medium",
  "Median of 2 sorted arrays": "Hard",
  "Kth element of 2 sorted arrays": "Medium",
  "Allocate Minimum Number of Pages": "Hard",
  "Aggressive Cows": "Hard",
  "Implement Max Heap": "Medium",
  "K-th Largest element in an array": "Medium",
  "Maximum Sum Combination": "Hard",
  "Find Median from Data Stream": "Hard",
  "Merge K Sorted Arrays": "Medium",
  "Top K Frequent Elements": "Medium",
  "Implement Stack using Arrays": "Easy",
  "Implement Queue using Arrays": "Easy",
  "Implement Stack using Queue (single queue)": "Easy",
  "Implement Queue using Stack": "Easy",
  "Balanced Parenthesis": "Easy",
  "Next Greater Element": "Medium",
  "Sort a Stack": "Medium",
  "Next Smaller Element": "Medium",
  "LRU Cache": "Medium",
  "LFU Cache": "Hard",
  "Largest rectangle in a histogram": "Hard",
  "Sliding Window Maximum": "Hard",
  "Implement Min Stack": "Hard",
  "Rotten Oranges": "Medium",
  "Stock span problem": "Hard",
  "Maximum of Minimums for Every Window Size": "Medium",
  "Celebrity Problem": "Hard",
  "Reverse every word in a string": "Medium",
  "Longest Palindrome in a string": "Medium",
  "Roman to Integer": "Medium",
  "Implement ATOI / STRSTR": "Medium",
  "Longest Common Prefix": "Easy",
  "Rabin Karp Algorithm": "Hard",
  "Z function": "Hard",
  "KMP Algorithm or LPS array": "Hard",
  "Minimum insertions to make string palindrome": "Hard",
  "Valid Anagram": "Easy",
  "Count and say": "Hard",
  "Compare version numbers": "Medium",
  "Inorder Traversal": "Easy",
  "Preorder Traversal": "Easy",
  "Postorder Traversal": "Easy",
  "Morris Inorder Traversal": "Hard",
  "Morris Preorder Traversal": "Hard",
  "Right/Left View of BT": "Medium",
  "Bottom view of BT": "Medium",
  "Top View of BT": "Medium",
  "Pre, Post, Inorder in one traversal": "Easy",
  "Vertical Order Traversal": "Medium",
  "Print root to leaf path in BT": "Medium",
  "Maximum Width of BT": "Medium",
  "Level Order Traversal": "Easy",
  "Maximum Depth in BT": "Medium",
  "Diameter of Binary Tree": "Easy",
  "Check for balanced binary tree": "Medium",
  "LCA in BT": "Hard",
  "Check if two trees are identical": "Medium",
  "Zig Zag / Spiral Traversal": "Medium",
  "Boundary Traversal": "Medium",
  "Maximum path sum": "Medium",
  "Construct BT from Preorder and Inorder": "Hard",
  "Construct BT from Postorder and Inorder": "Hard",
  "Symmetric Binary Tree": "Medium",
  "Flatten Binary Tree to Linked List": "Medium",
  "Check for symmetrical BTs": "Medium",
  "Children Sum Property": "Medium",
  "Populating Next Right Pointers": "Medium",
  "Search in BST": "Easy",
  "Construct BST from given keys": "Easy",
  "Construct BST from preorder traversal": "Medium",
  "Check if a tree is a BST": "Medium",
  "LCA in BST": "Medium",
  "Inorder successor and predecessor in BST": "Medium",
  "Floor in a BST": "Easy",
  "Ceil in a BST": "Easy",
  "Find K-th smallest element in BST": "Medium",
  "Kth Smallest and Largest element in BST": "Medium",
  "Two sum in BST": "Hard",
  "BST iterator": "Hard",
  "Size of the largest BST in a Binary Tree": "Hard",
  "Serialize and De-serialize BT": "Hard",
  "Binary Tree to Doubly Linked List": "Medium",
  "Find Median in a Stream": "Medium",
  "Kth largest element in a stream": "Hard",
  "Distinct Numbers in Each Subarray": "Medium",
  "K-th largest element in an unsorted array": "Medium",
  "Flood-fill Algorithm": "Medium",
  "Clone Graph": "Medium",
  DFS: "Medium",
  "Traversal Techniques": "Medium",
  "Detect cycle in Undirected Graph (BFS)": "Hard",
  "Detect cycle in Undirected Graph (DFS)": "Hard",
  "Detect cycle in Directed Graph (DFS)": "Hard",
  "Detect cycle in Directed Graph (BFS)": "Hard",
  "Topological Sort BFS": "Hard",
  "Topological Sort DFS": "Hard",
  "Number of Islands": "Medium",
  "Bipartite Graph": "Hard",
  "Bipartite Check using DFS": "Hard",
  "Strongly Connected Component (Kosaraju)": "Hard",
  "Dijkstra's Algorithm": "Hard",
  "Bellman Ford Algorithm": "Hard",
  "Floyd Warshall Algorithm": "Hard",
  "MST using Prim's": "Hard",
  "MST using Kruskal": "Hard",
  "Max Product Subarray": "Hard",
  "Longest Increasing Subsequence": "Medium",
  "Longest Common Subsequence": "Hard",
  "0/1 Knapsack": "Hard",
  "Edit Distance": "Hard",
  "Maximum Sum Increasing Subsequence": "Medium",
  "Matrix Chain Multiplication": "Hard",
  "Minimum Sum Path in Matrix": "Medium",
  "Coin Change II": "Hard",
  "Subset Sum equals target": "Hard",
  "Rod Cutting Problem": "Hard",
  "Super Egg Drop": "Medium",
  "Word Break": "Medium",
  "Palindrome Partitioning (MCM Variation)": "Hard",
  "Maximum Profit in Job Scheduling": "Medium",
  "Trie Implementation and Operations": "Hard",
  "Trie Implementation and Advanced Operations": "Hard",
  "Longest Word with All Prefixes": "Medium",
  "Number of distinct substrings in a string": "Medium",
  "Power Set": "Medium",
  "Maximum XOR of two numbers in an array": "Not Specified",
};

// Added: transform roadmap questions into {title, difficulty} objects for UI rendering.
export const DSA_ROADMAP = ROADMAP_TOPICS.map((topic) => ({
  ...topic,
  questions: topic.questions.map((title) => ({
    title,
    difficulty: DIFFICULTY_BY_QUESTION[title] || "Not Specified",
  })),
}));
